app:
  app_host: 127.0.0.1
  app_sign_expire: 60
  run_mode: dev
  http_port: 8820
  read_timeout: 60
  write_timeout: 60
  runtime_root_path: runtime/
  app_log_path: logs/log.log
#23.105.204.29:3307 127.0.0.1:3306
mysql:
  dbname: bourse
  user: root
  password: IcWw%%r3pt
  host: 34.87.88.149:3307
  max_open_conn: 1000
  max_idle_conn: 100
  conn_max_life_second: 30
  table_prefix: bo_

redis:
  host: 34.126.77.164:6379
  db: 0
  password: LvuN2seeDH
  min_idle_conn: 500
  pool_size: 100
  max_retries: 3

rabbitMQ:
  mqurl: amqp://admin:password@34.126.77.164:5672

mongodb:
  dbname: bourse
  user: test
  password: test
  host: 34.126.77.164:27018

elasticsearch:
  url: http://127.0.0.1:9200
  user: bourse
  password: test
  bulk_action_num: 1000
  bulk_action_size: 20480
  bulk_workers_num: 10


